<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>CS2_Echo.UI</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Assets\favicon.ico</ApplicationIcon>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Markdig.Wpf" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Velopack" />
    <PackageReference Include="WPF-UI" />
    <PackageReference Include="WPF-UI.DependencyInjection" />
    <PackageReference Include="WPF-UI.Tray" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CS2-Echo.Logic\CS2-Echo.Logic.csproj" />
    <ProjectReference Include="..\CS2-Echo.Infrastructure\CS2-Echo.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\favicon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
